// 한국 주요 상장 종목 리스트 (KOSPI + KOSDAQ)
// 검색용 로컬 데이터 - 외부 API 의존 없이 즉시 검색 가능

export interface StockItem {
  symbol: string;
  name: string;
  market: 'KOSPI' | 'KOSDAQ';
}

export const STOCK_LIST: StockItem[] = [
  // === KOSPI 주요 종목 ===
  { symbol: '005930', name: '삼성전자', market: 'KOSPI' },
  { symbol: '000660', name: 'SK하이닉스', market: 'KOSPI' },
  { symbol: '373220', name: 'LG에너지솔루션', market: 'KOSPI' },
  { symbol: '005490', name: 'POSCO홀딩스', market: 'KOSPI' },
  { symbol: '035420', name: 'NAVER', market: 'KOSPI' },
  { symbol: '000270', name: '기아', market: 'KOSPI' },
  { symbol: '005380', name: '현대차', market: 'KOSPI' },
  { symbol: '006400', name: '삼성SDI', market: 'KOSPI' },
  { symbol: '051910', name: 'LG화학', market: 'KOSPI' },
  { symbol: '035720', name: '카카오', market: 'KOSPI' },
  { symbol: '055550', name: '신한지주', market: 'KOSPI' },
  { symbol: '105560', name: 'KB금융', market: 'KOSPI' },
  { symbol: '012330', name: '현대모비스', market: 'KOSPI' },
  { symbol: '066570', name: 'LG전자', market: 'KOSPI' },
  { symbol: '003670', name: '포스코퓨처엠', market: 'KOSPI' },
  { symbol: '028260', name: '삼성물산', market: 'KOSPI' },
  { symbol: '086790', name: '하나금융지주', market: 'KOSPI' },
  { symbol: '003550', name: 'LG', market: 'KOSPI' },
  { symbol: '034730', name: 'SK', market: 'KOSPI' },
  { symbol: '032830', name: '삼성생명', market: 'KOSPI' },
  { symbol: '015760', name: '한국전력', market: 'KOSPI' },
  { symbol: '017670', name: 'SK텔레콤', market: 'KOSPI' },
  { symbol: '009150', name: '삼성전기', market: 'KOSPI' },
  { symbol: '316140', name: '우리금융지주', market: 'KOSPI' },
  { symbol: '030200', name: 'KT', market: 'KOSPI' },
  { symbol: '010130', name: '고려아연', market: 'KOSPI' },
  { symbol: '034020', name: '두산에너빌리티', market: 'KOSPI' },
  { symbol: '033780', name: 'KT&G', market: 'KOSPI' },
  { symbol: '096770', name: 'SK이노베이션', market: 'KOSPI' },
  { symbol: '011200', name: 'HMM', market: 'KOSPI' },
  { symbol: '018260', name: '삼성에스디에스', market: 'KOSPI' },
  { symbol: '010950', name: 'S-Oil', market: 'KOSPI' },
  { symbol: '003490', name: '대한항공', market: 'KOSPI' },
  { symbol: '024110', name: '기업은행', market: 'KOSPI' },
  { symbol: '009540', name: '한국조선해양', market: 'KOSPI' },
  { symbol: '011170', name: '롯데케미칼', market: 'KOSPI' },
  { symbol: '036570', name: '엔씨소프트', market: 'KOSPI' },
  { symbol: '000810', name: '삼성화재', market: 'KOSPI' },
  { symbol: '161390', name: '한국타이어앤테크놀로지', market: 'KOSPI' },
  { symbol: '352820', name: '하이브', market: 'KOSPI' },
  { symbol: '011780', name: '금호석유', market: 'KOSPI' },
  { symbol: '010140', name: '삼성중공업', market: 'KOSPI' },
  { symbol: '259960', name: '크래프톤', market: 'KOSPI' },
  { symbol: '004020', name: '현대제철', market: 'KOSPI' },
  { symbol: '006800', name: '미래에셋증권', market: 'KOSPI' },
  { symbol: '000720', name: '현대건설', market: 'KOSPI' },
  { symbol: '267250', name: 'HD현대', market: 'KOSPI' },
  { symbol: '009830', name: '한화솔루션', market: 'KOSPI' },
  { symbol: '329180', name: 'HD현대중공업', market: 'KOSPI' },
  { symbol: '138040', name: '메리츠금융지주', market: 'KOSPI' },
  { symbol: '047050', name: '포스코인터내셔널', market: 'KOSPI' },
  { symbol: '090430', name: '아모레퍼시픽', market: 'KOSPI' },
  { symbol: '323410', name: '카카오뱅크', market: 'KOSPI' },
  { symbol: '402340', name: 'SK스퀘어', market: 'KOSPI' },
  { symbol: '069500', name: 'KODEX 200', market: 'KOSPI' },
  { symbol: '005935', name: '삼성전자우', market: 'KOSPI' },
  { symbol: '078930', name: 'GS', market: 'KOSPI' },
  { symbol: '036460', name: '한국가스공사', market: 'KOSPI' },
  { symbol: '001570', name: '금양', market: 'KOSPI' },
  { symbol: '180640', name: '한진칼', market: 'KOSPI' },
  { symbol: '071050', name: '한국금융지주', market: 'KOSPI' },
  { symbol: '016360', name: '삼성증권', market: 'KOSPI' },
  { symbol: '004990', name: '롯데지주', market: 'KOSPI' },
  { symbol: '011070', name: 'LG이노텍', market: 'KOSPI' },
  { symbol: '326030', name: 'SK바이오팜', market: 'KOSPI' },
  { symbol: '383220', name: 'F&F', market: 'KOSPI' },
  { symbol: '302440', name: 'SK바이오사이언스', market: 'KOSPI' },
  { symbol: '241560', name: '두산밥캣', market: 'KOSPI' },
  { symbol: '000100', name: '유한양행', market: 'KOSPI' },
  { symbol: '021240', name: '코웨이', market: 'KOSPI' },
  { symbol: '272210', name: '한화시스템', market: 'KOSPI' },
  { symbol: '006360', name: 'GS건설', market: 'KOSPI' },
  { symbol: '047810', name: '한국항공우주', market: 'KOSPI' },
  { symbol: '282330', name: 'BGF리테일', market: 'KOSPI' },
  { symbol: '003410', name: '쌍용C&E', market: 'KOSPI' },
  { symbol: '051900', name: 'LG생활건강', market: 'KOSPI' },
  { symbol: '032640', name: 'LG유플러스', market: 'KOSPI' },
  { symbol: '007070', name: 'GS리테일', market: 'KOSPI' },
  { symbol: '088980', name: '맥쿼리인프라', market: 'KOSPI' },

  // === KOSDAQ 주요 종목 ===
  { symbol: '247540', name: '에코프로비엠', market: 'KOSDAQ' },
  { symbol: '086520', name: '에코프로', market: 'KOSDAQ' },
  { symbol: '263750', name: '펄어비스', market: 'KOSDAQ' },
  { symbol: '293490', name: '카카오게임즈', market: 'KOSDAQ' },
  { symbol: '196170', name: '알테오젠', market: 'KOSDAQ' },
  { symbol: '403870', name: 'HPSP', market: 'KOSDAQ' },
  { symbol: '041510', name: 'SM', market: 'KOSDAQ' },
  { symbol: '112040', name: '위메이드', market: 'KOSDAQ' },
  { symbol: '145020', name: '휴젤', market: 'KOSDAQ' },
  { symbol: '328130', name: '루닛', market: 'KOSDAQ' },
  { symbol: '036930', name: '주성엔지니어링', market: 'KOSDAQ' },
  { symbol: '277810', name: '레인보우로보틱스', market: 'KOSDAQ' },
  { symbol: '068760', name: '셀트리온제약', market: 'KOSDAQ' },
  { symbol: '039030', name: '이오테크닉스', market: 'KOSDAQ' },
  { symbol: '357780', name: '솔브레인', market: 'KOSDAQ' },
  { symbol: '095340', name: 'ISC', market: 'KOSDAQ' },
  { symbol: '058470', name: '리노공업', market: 'KOSDAQ' },
  { symbol: '067630', name: 'HLB생명과학', market: 'KOSDAQ' },
  { symbol: '028300', name: 'HLB', market: 'KOSDAQ' },
  { symbol: '048410', name: '현대바이오', market: 'KOSDAQ' },
  { symbol: '091990', name: '셀트리온헬스케어', market: 'KOSDAQ' },
  { symbol: '214150', name: '클래시스', market: 'KOSDAQ' },
  { symbol: '035900', name: 'JYP Ent.', market: 'KOSDAQ' },
  { symbol: '257720', name: '실리콘투', market: 'KOSDAQ' },
  { symbol: '060310', name: '3S', market: 'KOSDAQ' },
  { symbol: '141080', name: '레고켐바이오', market: 'KOSDAQ' },
  { symbol: '240810', name: '원익IPS', market: 'KOSDAQ' },
  { symbol: '078340', name: '컴투스', market: 'KOSDAQ' },
  { symbol: '033640', name: '네패스', market: 'KOSDAQ' },
  { symbol: '253450', name: '스튜디오드래곤', market: 'KOSDAQ' },
  { symbol: '131970', name: '테스나', market: 'KOSDAQ' },
  { symbol: '041190', name: '우리기술투자', market: 'KOSDAQ' },
  { symbol: '098460', name: '고영', market: 'KOSDAQ' },
  { symbol: '031510', name: '오스템임플란트', market: 'KOSDAQ' },
  { symbol: '223220', name: 'DBR', market: 'KOSDAQ' },
  { symbol: '299030', name: '하나기술', market: 'KOSDAQ' },
  { symbol: '090460', name: '비에이치', market: 'KOSDAQ' },
  { symbol: '383310', name: '엘앤에프', market: 'KOSDAQ' },
  { symbol: '235980', name: '메드팩토', market: 'KOSDAQ' },
  { symbol: '122870', name: '와이지엔터테인먼트', market: 'KOSDAQ' },
];

// 종목 검색 (이름 또는 코드로)
export function searchLocalStocks(query: string): StockItem[] {
  if (!query || query.length < 1) return [];

  const q = query.toLowerCase().trim();

  return STOCK_LIST.filter(
    (stock) =>
      stock.name.toLowerCase().includes(q) ||
      stock.symbol.includes(q)
  ).slice(0, 10);
}
